# POST  http://localhost:5000/api/user
# Content-Type: application/json

# {
#     "name": "John",
#     "lastname": "Wick",
#     "Login": "JohnW232222",
#     "password" : "ilovemydog",
#     "role" : "User",
#     "info" : "killer"
# }

  
# POST  http://localhost:5000/api/taskNote
# Content-Type: application/json

# {
#     "userId": 1,
#     "header": "To do",
#     "description": "to do home task",
#     # "priority" : "null",
#     # "creationTime" : "1234",
#     "Complete" : false
# }

  

# POST  http://localhost:5000/api/auth/authenticate
# Content-Type: application/json

# {
#     "Login": "jb00722",
#     "Password" : "spy",
#     "name": "John",
#     "lastname": "Wick",
#     "role" : "User",
#     "info" : "killer"
# }


POST  http://localhost:5000/api/taskNote
Content-Type: application/json

{
    "Header": "jb00722",
    "Description" : "spy",
    "userId": 1,
    "Complete": false,
    "Priority" : "important",
    "CreationTime" : "2012-01-26T13:51:50.417-07:00"
}



